package com.bage.finance.biz.domain;

import java.util.Date;

/**
 * 凭证字配置（表：voucher_word_config）
 *
 * @author bage
 * @date 2024-03-07 15:17:17
 */
public class VoucherWordConfig {
    /**
     * 
     */
    private Long id;

    /**
     * 凭证纸字
     */
    private String voucherWord;

    /**
     * 打印标题
     */
    private String printTitle;

    /**
     * 是否是默认[0:否，1：默认]
     */
    private Boolean defaultFlag;

    /**
     * 租户id
     */
    private Long tenantId;

    /**
     * 是否禁用
     */
    private Boolean disable;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date updateTime;

    /**
     * 用户id
     */
    private Long memberId;

    /**
     * 修改用户id
     */
    private Long updateMemberId;

    /**
     * 是否删除，0：删除，1：未删除
     */
    private Boolean delFlag;

    /**
     * 使用计数
     */
    private Integer useCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.id
     *
     * @return the value of voucher_word_config.id
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.id
     *
     * @param id the value for voucher_word_config.id
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.voucher_word
     *
     * @return the value of voucher_word_config.voucher_word
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public String getVoucherWord() {
        return voucherWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.voucher_word
     *
     * @param voucherWord the value for voucher_word_config.voucher_word
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setVoucherWord(String voucherWord) {
        this.voucherWord = voucherWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.print_title
     *
     * @return the value of voucher_word_config.print_title
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public String getPrintTitle() {
        return printTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.print_title
     *
     * @param printTitle the value for voucher_word_config.print_title
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setPrintTitle(String printTitle) {
        this.printTitle = printTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.default_flag
     *
     * @return the value of voucher_word_config.default_flag
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public Boolean getDefaultFlag() {
        return defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.default_flag
     *
     * @param defaultFlag the value for voucher_word_config.default_flag
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setDefaultFlag(Boolean defaultFlag) {
        this.defaultFlag = defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.tenant_id
     *
     * @return the value of voucher_word_config.tenant_id
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.tenant_id
     *
     * @param tenantId the value for voucher_word_config.tenant_id
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.disable
     *
     * @return the value of voucher_word_config.disable
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public Boolean getDisable() {
        return disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.disable
     *
     * @param disable the value for voucher_word_config.disable
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setDisable(Boolean disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.create_time
     *
     * @return the value of voucher_word_config.create_time
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.create_time
     *
     * @param createTime the value for voucher_word_config.create_time
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.update_time
     *
     * @return the value of voucher_word_config.update_time
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.update_time
     *
     * @param updateTime the value for voucher_word_config.update_time
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.member_id
     *
     * @return the value of voucher_word_config.member_id
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.member_id
     *
     * @param memberId the value for voucher_word_config.member_id
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.update_member_id
     *
     * @return the value of voucher_word_config.update_member_id
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public Long getUpdateMemberId() {
        return updateMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.update_member_id
     *
     * @param updateMemberId the value for voucher_word_config.update_member_id
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setUpdateMemberId(Long updateMemberId) {
        this.updateMemberId = updateMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.del_flag
     *
     * @return the value of voucher_word_config.del_flag
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.del_flag
     *
     * @param delFlag the value for voucher_word_config.del_flag
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column voucher_word_config.use_count
     *
     * @return the value of voucher_word_config.use_count
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public Integer getUseCount() {
        return useCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column voucher_word_config.use_count
     *
     * @param useCount the value for voucher_word_config.use_count
     *
     * @mbg.generated Thu Mar 07 15:17:17 CST 2024
     */
    public void setUseCount(Integer useCount) {
        this.useCount = useCount;
    }

    public void initDefault() {
        if (this.getVoucherWord() == null) {
            this.setVoucherWord("");
        }
        if (this.getPrintTitle() == null) {
            this.setPrintTitle("");
        }
        if (this.getDefaultFlag() == null) {
            this.setDefaultFlag(false);
        }
        if (this.getTenantId() == null) {
            this.setTenantId(0L);
        }
        if (this.getDisable() == null) {
            this.setDisable(false);
        }
        if (this.getCreateTime() == null) {
            this.setCreateTime(new Date());
        }
        if (this.getUpdateTime() == null) {
            this.setUpdateTime(new Date());
        }
        if (this.getMemberId() == null) {
            this.setMemberId(0L);
        }
        if (this.getUpdateMemberId() == null) {
            this.setUpdateMemberId(0L);
        }
        if (this.getDelFlag() == null) {
            this.setDelFlag(false);
        }
        if (this.getUseCount() == null) {
            this.setUseCount(0);
        }
    }

    public void initUpdate() {
    }
}